baseURL = "https://semicomplete.com/"
languageCode = "en-us"
title = "semicomplete"
theme = "whiteplain"

copyright = "&copy; Copyright 2006-2022 Jordan Sissel - Content licensed as <a href='https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode'>CC BY-NC-SA</a>"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  showShareIcons = false
  dateFormat = "2 January, 2006"

[params.author]
  name = "Jordan Sissel"
  gravatar = "jls@semicomplete.com"
  twitter = "jordansissel"
  github = "jordansissel"

# Header Menu
[[menu.main]]
  name = "Categories"
  identifier = "categories"
  url = "/categories/"
  weight = 1
[[menu.main]]
  name = "Tags"
  identifier = "tags"
  url = "/tags/"
  weight = 2
[[menu.main]]
  name = "Archives"
  identifier = "archives"
  url = "/archives/"
  weight = 3
[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
  weight = 4

# Footer Menu
[[menu.footer]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/about/"

[markup.goldmark.renderer]
  unsafe = true
  
